version: '3'

tasks:
  multimod:
    dir: tools
    cmds:
      - 'go run go.opentelemetry.io/build-tools/multimod'
  multimod-verify:
    dir: tools
    cmds:
      - 'go run go.opentelemetry.io/build-tools/multimod verify'
  multimod-prerelease:
    dir: tools
    cmds:
      - 'go run go.opentelemetry.io/build-tools/multimod prerelease --module-set-name stable-v0'
  multimod-tag:
    dir: tools
    cmds:
      - 'go run go.opentelemetry.io/build-tools/multimod tag --module-set-name stable-v0 --print-tags --commit-hash {{.HASH}}'
    requires:
      vars: [HASH]
  update-version:
    cmds:
      - 'cd sq/structargs; go mod edit -require=github.com/rrgmc/litsql@{{.VERSION}}'
      - 'cd sq/reflectxargs; go mod edit -require=github.com/rrgmc/litsql@{{.VERSION}}'
    requires:
      vars: [VERSION]
  current-version:
    cmds:
      - 'echo "Version: {{.GIT_TAG_CURRENT}}"'
    silent: true
    vars:
      GIT_TAG_CURRENT:
        sh: 'git describe --tags --abbrev=0'
  release-version:
    cmds:
      - 'echo "Version: {{.GIT_TAG_CURRENT}} => {{.VERSION}}"'
      - task: release-version-internal
    vars:
      GIT_TAG_CURRENT:
        sh: 'git describe --tags --abbrev=0'
    requires:
      vars: [VERSION]
    preconditions:
      - sh: 'test -z "$(git status --porcelain)"'
        msg: 'there are uncommited git changes'
    silent: true
  release-version-internal:
    internal: true
    prompt: "Creating and pushing tag {{.VERSION}}. Are you sure?"
    cmds:
      - 'git tag sq/structargs/{{.VERSION}}'
      - 'git tag sq/reflectxargs/{{.VERSION}}'
      - 'git tag {{.VERSION}}'
      - 'git push --tags'
    requires:
      vars: [VERSION]
