// Code generated by "litsql-dialectgen"; DO NOT EDIT.
package sm

import (
	tag "github.com/rrgmc/litsql/dialect/psql/tag"
	sq "github.com/rrgmc/litsql/sq"
	chain "github.com/rrgmc/litsql/sq/chain"
)

type FromChain = chain.From[tag.SelectTag]

type GroupByChain interface {
	sq.QueryMod[tag.SelectTag]
	Distinct() GroupByChain
}

type JoinChain = chain.Join[tag.SelectTag]

type WindowChain = chain.Window[tag.SelectTag]

type WithChain = chain.With[tag.SelectTag]
