dialects:
  psql:
    mods:
#      dm:
#        funcs:
#          - prefix: Using
#            secondTypeParam: SelectTag
#      im:
#        funcs:
#          - prefix: Query
#            secondTypeParam: SelectTag
#      um:
#        funcs:
#          - prefix: FromQuery
#            secondTypeParam: SelectTag
  sqlite:
    mods:
      sm:
        chains:
          From:
            methods:
              - As
#      dm:
#        funcs:
#          - prefix: Using
#            secondTypeParam: SelectTag
      im:
        funcs:
          - prefix: Where
            replacePrefix: ConflictWhere
#          - prefix: Query
#            secondTypeParam: SelectTag
