dialects:
  sqlite:
    mods:
      sm:
        chains:
          From:
            methods:
              - As
      im:
        skip:
          - OverridingSystem
          - OverridingUser
  mysql:
      im:
        skip:
          - OverridingSystem
          - OverridingUser
