dialects:
  sqlite:
    mods:
      sm:
        chains:
          From:
            methods: ['As']
      im:
        skip: ['OverridingSystem', 'OverridingUser']
  mysql:
    mods:
      sm:
        chains:
          From:
            methods: ['As', 'Lateral']
      im:
        skip: ['OverridingSystem', 'OverridingUser']
