dialects:
  psql:
    default:
      chains:
        From:
          methods: ['As', 'Lateral']
        GroupBy:
          methods: ['Distinct']
  sqlite:
    default:
      chains:
        From:
          methods: ['As']
        GroupBy:
          methods: ['Distinct']
        Join:
          methods: ['As', 'Lateral', 'Natural', 'On', 'OnExpr', 'OnClause', 'Using']
        With:
          methods: ['As', 'NotMaterialized', 'Materialized']
    mods:
      im:
        skip: ['OverridingSystem', 'OverridingUser']
  mysql:
    default:
      chains:
        From:
          methods: ['As', 'Lateral']
        GroupBy:
          methods: ['With']
        Join:
          methods: ['As', 'Lateral', 'Natural', 'On', 'OnExpr', 'OnClause', 'Using']
        With:
          methods: ['As', 'Recursive']
    mods:
      im:
        skip: ['OverridingSystem', 'OverridingUser']
