dialects:
  sqlite:
    mods:
      sm:
        chains:
          From:
            methods:
              - As
      dm:
        funcs:
          - prefix: Using
            secondTypeParam: SelectTag
      im:
        funcs:
          - prefix: Where
            replacePrefix: ConflictWhere
          - prefix: Query
            secondTypeParam: SelectTag
