dialects:
  sqlite:
    mods:
      sm:
        chains:
          From:
            methods:
              - As
      im:
        funcs:
          - prefix: Where
            replacePrefix: ConflictWhere
