dialects:
  psql:
    default:
      chains:
        GroupBy:
          methods: ['Distinct']
  sqlite:
    default:
      chains:
        From:
          methods: ['As']
        GroupBy:
          methods: ['Distinct']
        Join:
          methods: ['As', 'Lateral', 'Natural', 'On', 'OnExpr', 'OnClause', 'Using']
        With:
          methods: ['As', 'NotMaterialized', 'Materialized']
  mysql:
    default:
      chains:
        From:
          methods: ['As', 'Lateral']
        GroupBy:
          methods: ['With']
        Join:
          methods: ['As', 'Lateral', 'Natural', 'On', 'OnExpr', 'OnClause', 'Using']
        Window:
          methods: ['From', 'PartitionBy', 'PartitionByExpr', 'OrderBy', 'OrderByExpr', 'Range', 'Rows', 'FromUnboundedPreceding', 'FromPreceding', 'FromCurrentRow', 'FromFollowing', 'ToPreceding', 'ToCurrentRow', 'ToFollowing', 'ToUnboundedFollowing']
        With:
          methods: ['As', 'Recursive']
