package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/types"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/rrgmc/litsql/internal/dialectgen/genutil"
	"golang.org/x/exp/maps"
	"golang.org/x/tools/go/packages"
)

var (
	dialect = flag.String("dialect", "", "dialect folder name (ex: psql, mysql, sqlite")
	dryRun  = flag.Bool("dry-run", false, "dry run")
)

func main() {
	flag.Parse()
	if len(*dialect) == 0 {
		fmt.Println("dialect is required")
		os.Exit(2)
	}

	err := runDialect()
	if err != nil {
		panic(err)
	}
}

func runDialect() error {
	config, err := LoadConfig()
	if err != nil {
		return err
	}

	chainDir := filepath.Clean(filepath.Join(getCurrentDir(), "..", "..", "sq", "chain"))
	chainPkg, err := genutil.PkgInfoFromPath(
		chainDir, packages.NeedName|packages.NeedTypes,
	)
	if err != nil {
		return fmt.Errorf("couldn't load chain package: %s", err)
	}

	for _, sdir := range []string{"sm", "im", "um", "dm"} {
		err := runPkg(config, sdir, chainPkg)
		if err != nil {
			return err
		}
	}
	return nil
}

func runPkg(config Config, sdir string, chainPkg *packages.Package) error {
	var sname string
	switch sdir {
	case "sm":
		sname = "Select"
	case "im":
		sname = "Insert"
	case "um":
		sname = "Update"
	case "dm":
		sname = "Delete"
	default:
		return fmt.Errorf("unknown sdir: %s", sdir)
	}

	sdialect := *dialect

	currentDir := getCurrentDir()
	ismDir := filepath.Clean(filepath.Join(currentDir, "..", "i"+sdir))
	dialectDir := filepath.Clean(filepath.Join(currentDir, "..", "..", "dialect"))
	curDialectDir := filepath.Join(dialectDir, sdialect)
	smDir := filepath.Join(curDialectDir, sdir)

	// rootpkg := "github.com/rrgmc/litsql"
	ispkg := "github.com/rrgmc/litsql/internal/i" + sdir
	isqpkg := "github.com/rrgmc/litsql/internal/isq"
	ichainpkg := "github.com/rrgmc/litsql/internal/ichain"
	// imodpkg := "github.com/rrgmc/litsql/internal/imod"
	sqpkg := "github.com/rrgmc/litsql/sq"
	// sqchainpkg := sqpkg + "/chain"
	sqmodpkg := sqpkg + "/mod"
	sdialectpkg := fmt.Sprintf("github.com/rrgmc/litsql/dialect/%s", sdialect)
	sdialecttagpkg := sdialectpkg + "/tag"

	sdialectTag := jen.Qual(sdialecttagpkg, sname+"Tag")
	ssecondaryTag := jen.Qual(sdialecttagpkg, "SelectTag")

	lpkg, err := genutil.PkgInfoFromPath(
		ismDir, packages.NeedName|packages.NeedSyntax|packages.NeedTypes,
	)
	if err != nil {
		return fmt.Errorf("couldn't load source package: %s", err)
	}

	customType := &genutil.CTFunc{
		FuncNamedType: func(st jen.Statement, tt *types.Named) *jen.Statement {
			if tt.Obj().Name() == "QueryMod" && tt.Obj().Pkg().Path() == sqpkg {
				// sq.QueryMod => psql.SelectMod
				return st.Add(jen.Qual(sdialectpkg, sname+"Mod"))
			} else if tt.Obj().Name() == "QueryModApply" && tt.Obj().Pkg().Path() == sqpkg {
				// sq.QueryModApply => psql.SelectModApply
				return st.Add(jen.Qual(sdialectpkg, sname+"ModApply"))
			} else if tt.Obj().Name() == "Query" && tt.Obj().Pkg().Path() == isqpkg {
				// isq.Query => psql.SelectQuery
				// return st.Add(jen.Qual(sdialectpkg, sname+"Query"))
				return st.Add(jen.Qual(sdialectpkg, "SelectQuery"))
				// } else if tt.Obj().Pkg().Name() == "chain" && tt.Obj().Pkg().Path() == sqchainpkg {
			} else if tt.Obj().Pkg().Name() == "ichain" && tt.Obj().Pkg().Path() == ichainpkg {
				// isq/chain.FromChain => FromChain
				return st.Add(jen.Id(tt.Obj().Name()))
			} else if tt.Obj().Pkg().Path() == sqmodpkg {
				// sq/mod/InsertConflictUpdateMod => InsertConflictUpdateMod
				return st.Add(jen.Id(tt.Obj().Name()))
			}
			return nil
		},
		FuncIsPointer: func(tt *types.Pointer) bool {
			tnamed, ok := tt.Elem().(*types.Named)
			if !ok {
				return true
			}
			if tnamed.Obj().Pkg().Name() == "ichain" && tnamed.Obj().Pkg().Path() == ichainpkg {
				return false
			}
			return true
		},
	}

	applyFuncConfig := func(name string, fconfig *ConfigDialectModFunc) string {
		if fconfig != nil {
			if fconfig.ReplacePrefix != "" {
				n, _ := strings.CutPrefix(name, fconfig.Prefix)
				name = fconfig.ReplacePrefix + n
			}
		}
		return name
	}

	// chains := map[string]int{}
	chains := map[string]*types.Named{}

	f := jen.NewFile(sdir)
	f.PackageComment("// Code generated by \"litsql-dialectgen\"; DO NOT EDIT.")

	if lpkg.Types != nil {
		// qual := types.RelativeTo(lpkg.Types)
		scope := lpkg.Types.Scope()
		for _, name := range scope.Names() {
			obj := scope.Lookup(name)
			if !obj.Exported() {
				continue // skip unexported names
			}
			funcTyp, ok := obj.(*types.Func)
			if !ok {
				continue
			}

			// skip functions
			if slices.ContainsFunc(config.FindDialectSkip(*dialect, sdir, []string{
				"RawQuery",
			}), func(s string) bool {
				return strings.HasPrefix(funcTyp.Name(), s)
			}) {
				continue
			}

			docFound := false
			var doc *ast.CommentGroup

			for _, fileAst := range lpkg.Syntax {
				ast.Inspect(fileAst, func(n ast.Node) bool {
					if docFound {
						return false
					}
					if aFunc, ok := n.(*ast.FuncDecl); ok {
						if aFunc.Name.Name == funcTyp.Name() {
							docFound = true
							doc = aFunc.Doc
						}
					}
					return !docFound
				})
				if docFound {
					break
				}
			}

			docLines, docDirectives := genutil.ParseDoc(doc)
			// check "dialects" directive
			if doc != nil && len(doc.List) > 0 {
				if !docDirectives.IsListValue("dialects", *dialect, true) {
					continue
				}
			}

			sig := funcTyp.Type().(*types.Signature)
			// fmt.Printf("%s\n", types.ObjectString(funcTyp, qual))

			if sig.Results().Len() != 1 {
				return fmt.Errorf("function '%s' must have only 1 return value", name)
			}

			var chainName string
			if sigResultType, stNamed := sig.Results().At(0).Type().(*types.Named); stNamed {
				// don't generate root Query call
				// fmt.Println(sigResultType.Obj().Name(), sigResultType.Obj().Pkg().Path())
				if sigResultType.Obj().Name() == "Query" && sigResultType.Obj().Pkg().Path() == sqpkg {
					continue
				}

				// // detect chain return
				// // fmt.Println(sigResultType.Obj().Pkg().Name(), sigResultType.Obj().Pkg().Path())
				// if sigResultType.Obj().Pkg().Name() == "ichain" && sigResultType.Obj().Pkg().Path() == ichainpkg {
				// 	// isChainRet = true
				// 	chainName = sigResultType.Obj().Name()
				// 	chains[sigResultType.Obj().Name()] = sigResultType.TypeParams().Len()
				// }
			} else if sigResultPtr, stPointer := sig.Results().At(0).Type().(*types.Pointer); stPointer {
				if sigResultType, stNamed := sigResultPtr.Elem().(*types.Named); stNamed {
					// detect chain return
					if sigResultType.Obj().Pkg().Name() == "ichain" && sigResultType.Obj().Pkg().Path() == ichainpkg {
						chainName = strings.TrimSuffix(sigResultType.Obj().Name(), "Chain")
						chains[chainName] = sigResultType
					}
				}
			}

			funcConfig := config.FindDialectFunc(*dialect, sdir, funcTyp.Name())

			funcName := applyFuncConfig(funcTyp.Name(), funcConfig)

			// f.Comment(types.ObjectString(funcTyp, qual))
			for _, docLine := range docLines {
				f.Comment(docLine)
			}
			f.Func().Id(funcName).
				ParamsFunc(genutil.AddParams(sig.Params(), sig.Variadic(), customType)).
				ParamsFunc(genutil.AddParams(sig.Results(), false, customType)).
				Block(
					jen.ReturnFunc(func(rgroup *jen.Group) {
						rblock := jen.Qual(ispkg, funcTyp.Name()).
							TypesFunc(func(tgroup *jen.Group) {
								for k := 0; k < sig.TypeParams().Len(); k++ {
									if k > 0 {
										if sig.TypeParams().At(k).Obj().Name() == "CHAIN" {
											if chainName != "" {
												tgroup.Add(jen.Id(chainName + "Chain"))
											} else {
												tgroup.Add(jen.Id("NOT_A_CHAIN"))
											}
										} else if funcConfig != nil && funcConfig.SecondTypeParam != "" {
											tgroup.Add(jen.Qual(sdialecttagpkg, funcConfig.SecondTypeParam))
										} else {
											tgroup.Add(ssecondaryTag)
										}
									} else {
										tgroup.Add(sdialectTag)
									}
								}
							}).
							CallFunc(func(pgroup *jen.Group) {
								for k := 0; k < sig.Params().Len(); k++ {
									sigParam := sig.Params().At(k)
									c := jen.Id(genutil.ParamName(k, sigParam))
									if sig.Variadic() && k == sig.Params().Len()-1 {
										c.Op("...")
									}
									pgroup.Add(c)
								}
							})

						// if isChainRet {
						// 	if dchain := config.FindDialectChain(*dialect, sdir, sigResultType.Obj().Name()); dchain != nil {
						// 		rgroup.Op("&").Id(genutil.InitialToLower(sigResultType.Obj().Name()) + "ChainAdapter").
						// 			Block(jen.Id("chain").Op(":").Add(rblock).Op(","))
						// 		return
						// 	}
						// }
						rgroup.Add(rblock)
					}),
				)

			f.Line()
		}
	}

	fnfile := filepath.Join(smDir, "fn.go")
	if !*dryRun {
		// fmt.Println(fnfile)
		fnFile, ferr := os.Create(fnfile)
		if ferr != nil {
			return ferr
		}
		defer fnFile.Close()
		err = f.Render(fnFile)
	} else {
		fmt.Println(strings.Repeat("=", 10), fnfile, strings.Repeat("=", 10))
		err = f.Render(os.Stdout)
	}
	if err != nil {
		return err
	}

	if len(chains) > 0 {
		chainNames := maps.Keys(chains)
		slices.Sort(chainNames)

		fchain := jen.NewFile(sdir)
		fchain.PackageComment("// Code generated by \"litsql-dialectgen\"; DO NOT EDIT.")

		for _, chain := range chainNames {
			chainTyp := chains[chain]

			currentName := chain + "Chain"
			dchain := config.FindDialectChain(*dialect, sdir, chain)

			fchain.Type().
				Id(currentName).
				InterfaceFunc(func(igroup *jen.Group) {
					igroup.Add(jen.Qual(sqpkg, "QueryMod").Types(sdialectTag))
					for cm := range chainTyp.NumMethods() {
						cmethod := chainTyp.Method(cm)
						if cmethod.Name() == "Apply" {
							continue
						}
						if dchain != nil && !slices.Contains(dchain.Methods, cmethod.Name()) {
							continue
						}
						csig := cmethod.Type().(*types.Signature)

						igroup.Add(jen.Id(cmethod.Name()).
							ParamsFunc(genutil.AddParams(csig.Params(), csig.Variadic(), customType)).
							Params(jen.Id(currentName)),
						)
					}
				})

			fchain.Line()
		}

		chainfile := filepath.Join(smDir, "chain.go")
		if !*dryRun {
			// fmt.Println(fnfile)
			chainFile, err := os.Create(chainfile)
			if err != nil {
				return err
			}
			defer chainFile.Close()
			err = fchain.Render(chainFile)
		} else {
			fmt.Println(strings.Repeat("=", 10), chainfile, strings.Repeat("=", 10))
			err = fchain.Render(os.Stdout)
		}
		if err != nil {
			return err
		}
	}

	return nil
}

func getCurrentDir() string {
	_, filename, _, ok := runtime.Caller(1)
	if !ok {
		panic("could not determine current directory")
	}
	return filepath.Dir(filename)
}
