package main

import (
	"fmt"
	"go/types"
	"os"
	"path/filepath"
	"runtime"

	"github.com/dave/jennifer/jen"
	"github.com/rrgmc/litsql/internal/dialectgen/genutil"
	"golang.org/x/tools/go/packages"
)

func main() {
	err := runPkg()
	if err != nil {
		panic(err)
	}
}

func getCurrentDir() string {
	_, filename, _, ok := runtime.Caller(1)
	if !ok {
		panic("could not determine current directory")
	}
	return filepath.Dir(filename)
}

func runPkg() error {
	sdir := "sm"
	sname := "Select"
	sdialect := "psql"

	currentDir := getCurrentDir()
	ismDir := filepath.Clean(filepath.Join(currentDir, "..", "i"+sdir))
	dialectDir := filepath.Clean(filepath.Join(currentDir, "..", "..", "dialect"))
	curDialectDir := filepath.Join(dialectDir, sdialect)
	smDir := filepath.Join(curDialectDir, sdir)

	ispkg := "github.com/rrgmc/litsql/internal/i" + sdir
	isqpkg := "github.com/rrgmc/litsql/internal/isq"
	sqpkg := "github.com/rrgmc/litsql/sq"
	sqchainpkg := "github.com/rrgmc/litsql/sq/chain"
	sdialectpkg := fmt.Sprintf("github.com/rrgmc/litsql/dialect/%s", sdialect)
	sdialecttagpkg := fmt.Sprintf("%s/tag", sdialectpkg)

	lpkg, err := genutil.PkgInfoFromPath(
		ismDir, packages.NeedName|packages.NeedSyntax|packages.NeedTypes,
	)
	if err != nil {
		return fmt.Errorf("couldn't load source package: %s", err)
	}

	f := jen.NewFile(sdir)
	f.PackageComment("// Code generated by \"litsql\"; DO NOT EDIT.")

	if lpkg.Types != nil {
		customNamedType := func(st jen.Statement, tt *types.Named) *jen.Statement {
			if tt.Obj().Name() == "QueryMod" && tt.Obj().Pkg().Path() == sqpkg {
				return st.Add(jen.Qual(sdialectpkg, sname+"Mod"))
			} else if tt.Obj().Name() == "QueryModApply" && tt.Obj().Pkg().Path() == sqpkg {
				return st.Add(jen.Qual(sdialectpkg, sname+"ModApply"))
			} else if tt.Obj().Name() == "Query" && tt.Obj().Pkg().Path() == isqpkg {
				return st.Add(jen.Qual(sdialectpkg, sname+"Query"))
			} else if tt.Obj().Pkg().Name() == "chain" && tt.Obj().Pkg().Path() == sqchainpkg {
				return st.Add(jen.Id(fmt.Sprintf("%sChain", tt.Obj().Name())))
			}
			return nil
		}

		// qual := types.RelativeTo(lpkg.Types)
		scope := lpkg.Types.Scope()
		for _, name := range scope.Names() {
			obj := scope.Lookup(name)
			if !obj.Exported() {
				continue // skip unexported names
			}
			funcTyp, ok := obj.(*types.Func)
			if !ok {
				continue
			}
			sig := funcTyp.Type().(*types.Signature)
			// fmt.Printf("%s\n", types.ObjectString(funcTyp, qual))

			if sig.Results().Len() != 1 {
				return fmt.Errorf("function '%s' must have only 1 return value", name)
			}

			// don't generate root Query call
			sigResult := sig.Results().At(0)
			if sigResultType, stNamed := sigResult.Type().(*types.Named); stNamed {
				// fmt.Println(sigResultType.Obj().Name(), sigResultType.Obj().Pkg().Path())
				if sigResultType.Obj().Name() == "Query" && sigResultType.Obj().Pkg().Path() == sqpkg {
					continue
				}
			}

			// f.Comment(types.ObjectString(funcTyp, qual))
			f.Func().Id(funcTyp.Name()).
				ParamsFunc(genutil.AddParams(sig.Params(), sig.Variadic(), customNamedType)).
				ParamsFunc(genutil.AddParams(sig.Results(), false, customNamedType)).
				Block(
					jen.Return(
						jen.Qual(ispkg, funcTyp.Name()).
							TypesFunc(func(tgroup *jen.Group) {
								for k := 0; k < sig.TypeParams().Len(); k++ {
									tgroup.Add(jen.Qual(sdialecttagpkg, sname+"Tag"))
								}
							}).
							CallFunc(func(pgroup *jen.Group) {
								for k := 0; k < sig.Params().Len(); k++ {
									sigParam := sig.Params().At(k)
									c := jen.Id(genutil.ParamName(k, sigParam))
									if sig.Variadic() && k == sig.Params().Len()-1 {
										c.Op("...")
									}
									pgroup.Add(c)
								}
							}),
					),
				)

			f.Line()
		}
	}

	fnfile := filepath.Join(smDir, "fn.go")
	// fmt.Println(fnfile)
	fnFile, err := os.Create(fnfile)
	if err != nil {
		return err
	}
	defer fnFile.Close()
	err = f.Render(fnFile)
	// err = f.Render(os.Stdout)
	if err != nil {
		return err
	}

	return nil
}
