// Code generated by "litsql-dialectgen"; DO NOT EDIT.
package dm

import (
	litsql "github.com/rrgmc/litsql"
	mysql "github.com/rrgmc/litsql/dialect/mysql"
	tag "github.com/rrgmc/litsql/dialect/mysql/tag"
	idm "github.com/rrgmc/litsql/internal/idm"
)

func Apply(f func(a mysql.DeleteModApply)) mysql.DeleteMod {
	return idm.Apply[tag.DeleteTag](f)
}

func CrossJoin(table string) JoinChain {
	return &joinChainAdapter{
		chain: idm.CrossJoin[tag.DeleteTag](table),
	}
}

func CrossJoinExpr(table litsql.Expression) JoinChain {
	return &joinChainAdapter{
		chain: idm.CrossJoinExpr[tag.DeleteTag](table),
	}
}

func From(table string) mysql.DeleteMod {
	return idm.From[tag.DeleteTag](table)
}

func FullJoin(table string) JoinChain {
	return &joinChainAdapter{
		chain: idm.FullJoin[tag.DeleteTag](table),
	}
}

func FullJoinExpr(table litsql.Expression) JoinChain {
	return &joinChainAdapter{
		chain: idm.FullJoinExpr[tag.DeleteTag](table),
	}
}

func InnerJoin(table string) JoinChain {
	return &joinChainAdapter{
		chain: idm.InnerJoin[tag.DeleteTag](table),
	}
}

func InnerJoinExpr(table litsql.Expression) JoinChain {
	return &joinChainAdapter{
		chain: idm.InnerJoinExpr[tag.DeleteTag](table),
	}
}

func LeftJoin(table string) JoinChain {
	return &joinChainAdapter{
		chain: idm.LeftJoin[tag.DeleteTag](table),
	}
}

func LeftJoinExpr(table litsql.Expression) JoinChain {
	return &joinChainAdapter{
		chain: idm.LeftJoinExpr[tag.DeleteTag](table),
	}
}

func Only() mysql.DeleteMod {
	return idm.Only[tag.DeleteTag]()
}

func Returning(clauses ...string) mysql.DeleteMod {
	return idm.Returning[tag.DeleteTag](clauses...)
}

func RightJoin(table string) JoinChain {
	return &joinChainAdapter{
		chain: idm.RightJoin[tag.DeleteTag](table),
	}
}

func RightJoinExpr(table litsql.Expression) JoinChain {
	return &joinChainAdapter{
		chain: idm.RightJoinExpr[tag.DeleteTag](table),
	}
}

func StraightJoin(table string) JoinChain {
	return &joinChainAdapter{
		chain: idm.StraightJoin[tag.DeleteTag](table),
	}
}

func StraightJoinExpr(table litsql.Expression) JoinChain {
	return &joinChainAdapter{
		chain: idm.StraightJoinExpr[tag.DeleteTag](table),
	}
}

func Using(table string) FromChain {
	return &fromChainAdapter{
		chain: idm.Using[tag.DeleteTag](table),
	}
}

func UsingExpr(table litsql.Expression) FromChain {
	return &fromChainAdapter{
		chain: idm.UsingExpr[tag.DeleteTag](table),
	}
}

func UsingQuery(q mysql.SelectQuery) FromChain {
	return &fromChainAdapter{
		chain: idm.UsingQuery[tag.DeleteTag, tag.SelectTag](q),
	}
}

func Where(condition string) mysql.DeleteMod {
	return idm.Where[tag.DeleteTag](condition)
}

func WhereClause(query string, args ...any) mysql.DeleteMod {
	return idm.WhereClause[tag.DeleteTag](query, args...)
}

func WhereExpr(condition litsql.Expression) mysql.DeleteMod {
	return idm.WhereExpr[tag.DeleteTag](condition)
}

func With(name string, columns ...string) WithChain {
	return idm.With[tag.DeleteTag](name, columns...)
}

func WithExpr(name string, columns ...litsql.Expression) WithChain {
	return idm.WithExpr[tag.DeleteTag](name, columns...)
}
