// Code generated by "litsql-dialectgen"; DO NOT EDIT.
package dm

import (
	litsql "github.com/rrgmc/litsql"
	psql "github.com/rrgmc/litsql/dialect/psql"
	tag "github.com/rrgmc/litsql/dialect/psql/tag"
	idm "github.com/rrgmc/litsql/internal/idm"
)

func Apply(f func(a psql.DeleteModApply)) psql.DeleteMod {
	return idm.Apply[tag.DeleteTag](f)
}

func CrossJoin(table string) JoinChain {
	return idm.CrossJoin[tag.DeleteTag, JoinChain](table)
}

func CrossJoinExpr(table litsql.Expression) JoinChain {
	return idm.CrossJoinExpr[tag.DeleteTag, JoinChain](table)
}

func From(table string) psql.DeleteMod {
	return idm.From[tag.DeleteTag](table)
}

func FullJoin(table string) JoinChain {
	return idm.FullJoin[tag.DeleteTag, JoinChain](table)
}

func FullJoinExpr(table litsql.Expression) JoinChain {
	return idm.FullJoinExpr[tag.DeleteTag, JoinChain](table)
}

func InnerJoin(table string) JoinChain {
	return idm.InnerJoin[tag.DeleteTag, JoinChain](table)
}

func InnerJoinExpr(table litsql.Expression) JoinChain {
	return idm.InnerJoinExpr[tag.DeleteTag, JoinChain](table)
}

func LeftJoin(table string) JoinChain {
	return idm.LeftJoin[tag.DeleteTag, JoinChain](table)
}

func LeftJoinExpr(table litsql.Expression) JoinChain {
	return idm.LeftJoinExpr[tag.DeleteTag, JoinChain](table)
}

func Only() psql.DeleteMod {
	return idm.Only[tag.DeleteTag]()
}

func Returning(clauses ...string) psql.DeleteMod {
	return idm.Returning[tag.DeleteTag](clauses...)
}

func RightJoin(table string) JoinChain {
	return idm.RightJoin[tag.DeleteTag, JoinChain](table)
}

func RightJoinExpr(table litsql.Expression) JoinChain {
	return idm.RightJoinExpr[tag.DeleteTag, JoinChain](table)
}

func StraightJoin(table string) JoinChain {
	return idm.StraightJoin[tag.DeleteTag, JoinChain](table)
}

func StraightJoinExpr(table litsql.Expression) JoinChain {
	return idm.StraightJoinExpr[tag.DeleteTag, JoinChain](table)
}

func Using(table string) FromChain {
	return idm.Using[tag.DeleteTag, FromChain](table)
}

func UsingExpr(table litsql.Expression) FromChain {
	return idm.UsingExpr[tag.DeleteTag, FromChain](table)
}

func UsingQuery(q psql.SelectQuery) FromChain {
	return idm.UsingQuery[tag.DeleteTag, FromChain, tag.SelectTag](q)
}

func Where(condition string) psql.DeleteMod {
	return idm.Where[tag.DeleteTag](condition)
}

func WhereClause(query string, args ...any) psql.DeleteMod {
	return idm.WhereClause[tag.DeleteTag](query, args...)
}

func WhereExpr(condition litsql.Expression) psql.DeleteMod {
	return idm.WhereExpr[tag.DeleteTag](condition)
}

func With(name string, columns ...string) WithChain {
	return idm.With[tag.DeleteTag, WithChain](name, columns...)
}

func WithExpr(name string, columns ...litsql.Expression) WithChain {
	return idm.WithExpr[tag.DeleteTag, WithChain](name, columns...)
}
