// Code generated by "litsql-dialectgen"; DO NOT EDIT.
package um

import (
	litsql "github.com/rrgmc/litsql"
	tag "github.com/rrgmc/litsql/dialect/sqlite/tag"
	sq "github.com/rrgmc/litsql/sq"
)

type FromChain interface {
	sq.QueryMod[tag.UpdateTag]
	As(alias string, columns ...string) FromChain
}

type JoinChain interface {
	sq.QueryMod[tag.UpdateTag]
	As(alias string, columns ...string) JoinChain
	Lateral() JoinChain
	Natural() JoinChain
	On(on string) JoinChain
	OnExpr(on litsql.Expression) JoinChain
	OnClause(query string, args ...any) JoinChain
	Using(using ...string) JoinChain
}

type WithChain interface {
	sq.QueryMod[tag.UpdateTag]
	As(q litsql.Query) WithChain
	NotMaterialized() WithChain
	Materialized() WithChain
}
