// Code generated by "litsql-dialectgen"; DO NOT EDIT.
package im

import (
	tag "github.com/rrgmc/litsql/dialect/mysql/tag"
	imod "github.com/rrgmc/litsql/internal/imod"
	chain "github.com/rrgmc/litsql/sq/chain"
)

type InsertConflictUpdateChain = chain.InsertConflictUpdate[tag.InsertTag, imod.InsertConflictUpdateModTag]

type WithChain = chain.With[tag.InsertTag]
