// Code generated by "litsql-dialectgen"; DO NOT EDIT.
package im

import (
	litsql "github.com/rrgmc/litsql"
	tag "github.com/rrgmc/litsql/dialect/mysql/tag"
	sq "github.com/rrgmc/litsql/sq"
)

type WithChain interface {
	sq.QueryMod[tag.InsertTag]
	As(q litsql.Query) WithChain
	Recursive() WithChain
}
